sensors:
  - bin1_left_camera_pointcloud
  - bin1_right_camera_pointcloud
bin1_left_camera_pointcloud:
    sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
    point_cloud_topic: /bin1/left/camera/points
    max_range: 1.0
    point_subsample: 1
    padding_offset: 0.1
    padding_scale: 1.0
    max_update_rate: 1.0
    filtered_cloud_topic: /bin1/left/camera/filtered_points
bin1_right_camera_pointcloud:
    sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
    point_cloud_topic: /bin1/right/camera/points
    max_range: 1.0
    point_subsample: 1
    padding_offset: 0.1
    padding_scale: 1.0
    max_update_rate: 1.0
    filtered_cloud_topic: /bin1/right/camera/filtered_points

# sensors:
#   - sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
#     point_cloud_topic: /bin1/left/camera/points
#     max_range: 1.0
#     point_subsample: 1
#     padding_offset: 0.1
#     padding_scale: 1.0
#     max_update_rate: 1.0
#     # filtered_cloud_topic: filtered_cloud
