sensors:
  - bin1_left_depth
  - bin1_right_depth

# https://robotics.stackexchange.com/a/113085/33542

bin1_left_depth:
    sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
    point_cloud_topic: /your_camera_topic/depth/points
    max_range: 5.0
    point_subsample: 1
    padding_offset: 0.1
    padding_scale: 1.0
    max_update_rate: 1.0
    filtered_cloud_topic: filtered_cloud
